FORMAT: 1A
HOST: www.m-standard.co.jp

# mypage watch list api

<em>建物・検索条件</em>のウォッチ機能を提供するためのAPIです

# Group WatchList

## 建物ウォッチ [/api/v1/me/watch_list/properties]

## 取得 [GET]

建物ウォッチを取得します

+ Request (application/json)
    + Body

            {

            }

+ Response 200 (application/json)
    + Attributes
        + property_watches (array[PropertyWatch])

## 登録 [POST]

建物ウォッチを追加します

+ Request (application/json)
    + Attributes (PropertyWatchCreate)

    + Body

            {
                "property_id": 123456,
                "rent": true,
                "buy": true
            }
+ Response 201 (application/json)
条件追加に成功した時のレスポンス (登録結果を返します)
    + Attributes (PropertyWatch)

    + Body

        {
            "property_id": 123456,
            "rent": true,
            "buy": true
        }

+ Response 400 (application/json)
rent / buy 両方とも false でリクエストが送られた時

    + Body

            {
                "message": "bad request"
            }

+ Response 401 (application/json)
認証できていない状態でAPIをコールした時のレスポンス

    + Body

            {
                "message": "unauthorized"
            }

+ Response 403 (application/json)
上限を超えてAPIをコールした時のレスポンス

    + Body

            {
                "message": "ウォッチ条件は50件までしか保存できません"
            }

## 削除 [DELETE]

建物ウォッチを削除します

+ Request (application/json)
    + Attributes
        + property_id (number, required) - ウォッチを削除する建物ID}
    + Body

            {
                "property_id": 12345
            }

+ Response 200 (application/json)
+ Response 401 (application/json)
+ Response 404 (application/json)

## 検索条件ウォッチ [/api/v1/me/watch_list/search_conditions]

## 取得 [GET]

検索条件ウォッチを取得します

+ Request (application/json)
    + Body

            {

            }

+ Response 200 (application/json)
    + Attributes
        + search_condition_watches (array[SearchConditionWatch])

## 登録 [POST]

検索条件ウォッチを追加します

+ Request (application/json)
    + Attributes
        + serialize_search_condition (string, required)

    + Body

            {
                "serialize_search_condition": "{}"
            }
+ Response 201 (application/json)
条件追加に成功した時のレスポンス (登録済みの検索条件ウォッチを渡してもこのレスポンスを返します)
    + Attributes (SearchConditionWatch)

    + Body

            {
                "id": 1234
            }

+ Response 401 (application/json)
認証できていない状態でAPIをコールした時のレスポンス

    + Body

            {
                "message": "unauthorized"
            }

+ Response 403 (application/json)
上限を超えてAPIをコールした時のレスポンス

    + Body

            {
                "message": "ウォッチは50件までしか保存できません"
            }

## 削除 [DELETE]

検索条件ウォッチを削除します

+ Request (application/json)
    + Attributes
      + search_condition_watch_id (number, required) - 削除する検索条件ウォッチのID

    + Body
            {
                "search_condition_watch_id": 5
            }

+ Response 200 (application/json)
    + Attributes ()
    + Body

            {
                "message": "success"
            }

+ Response 401 (application/json)
認証できていない状態でAPIをコールした時のレスポンス

    + Body

            {
                "message": "unauthorized"
            }

+ Response 404 (application/json)
存在しない・自分に紐付いていない検索条件ウォッチのIDを指定した時のレスポンス

    + Body

            {
                "message": "not found"
            }

# Data Structures

## PropertyWatch
+ property_id: 1 (number) - ID
+ property_name: `六本木ヒルズレジデンス` (string) - 建物名
+ property_image_url: `https://assets.m-standard.co.jp/public/properties/0001/thumb/w750h460/image.jpg` (string) - 建物URL
+ layouts: `1R`, `1K`,`3LDK` (array[string]) - 間取り
+ age: (Age) - 築年数
+ nearest_station: (NearestStation) - 最寄り駅
+ rent: `true` (boolean) - 賃貸部屋をウォッチするか
+ buy: `true` (boolean) - 販売中部屋をウォッチするか
+ created_at: `yyyy-MM-ddThh:mm:ss.SSSZ` (string) - when created
+ updated_at: `yyyy-MM-ddThh:mm:ss.SSSZ` (string) - when updated

## PropertyWatchCreate
+ property_id (number, required)
    ウォッチする建物のID
+ rent (boolean, optional)
    賃貸物件をウォッチするか。ウォッチする場合はtrue
    + Default: true
+ buy (boolean, optional)
    売買物件をウォッチするか。ウォッチする場合はtrue
    + Default: true

## Age
+ year: 2007 (number) - 築年
+ month: 12 (number) - 築月
+ age: 13 (number) - 築年数

## NearestStation
+ railway: (Railway) - 路線
+ station: (Station) - 駅
+ walk_minute: 5 (number) - 徒歩時間

## Railway
+ name: `東京メトロ千代田線` (string) - 路線名
+ query: `28005_L` (string) - リンク時のパスパラメータ

## Station
+ name: `乃木坂駅` (string) - 駅名
+ query: `2800516_S` (string) - リンク時のパス

## SearchConditionWatch
+ search_condition_watch_id: 1 (number) - ID
+ search_type: `rent` (string) - 検索種別 (rent か buy )
+ search_condition: `港区 1LDK` (string) - 表示用の検索条件
+ search_condition_query: `34_CI/5_JA/` (string) - URLに付与する検索条件
+ created_at: `yyyy-MM-ddThh:mm:ss.SSSZ` (string) - when created
+ updated_at: `yyyy-MM-ddThh:mm:ss.SSSZ` (string) - when updated

## SearchConditionWatchCreateParams
+ serialize_search_condition: ``  (string,required)
+ search_type: `rent` (string, required) - 検索種別 (rent か buy )